//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MyCalendar.rc
//
#define IDC_MYICON                      2
#define MYMENU                          3
#define IDBUFEDIT                       4
#define IDD_SETTINGS                    5
#define INPUTBOXBUF                     6
#define TXTBOXDLG                       7
#define IDMONTHUP                       8
#define IDBUFEDIT2                      9
#define IDDAYUP                         9
#define IDMONTHDOWN                     10
#define IDYEARUP                        11
#define IDYEARDOWN                      12
#define IDDAYDOWN                       13
#define IDD_MYCALENDAR_DIALOG           102
#define IDS_APP_TITLE                   103
#define ID_HELP                         104
#define IDM_EXIT                        105
#define IDI_MYCALENDAR                  107
#define IDI_SMALL                       108
#define Calendar                        108
#define IDC_MYCALENDAR                  109
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDDEBUG                         130
#define IDBUFCHANGE                     131
#define IDWORDWRAP                      132
#define IDDATAWIPE                      133
#define IDR_MENU1                       134
#define IDDEBUG2                        134
#define IDD_DIALOG2                     136
#define IDB_BITMAP1                     141
#define IDD_DIALOG3                     144
#define IDINPUTSCRIPTBX                 144
#define IDD_DIALOG4                     145
#define IDSCRIPTDATE                    145
#define IDSCRIPTMACRO                   145
#define IDD_DIALOG5                     146
#define IDSCRIPTDATES                   146
#define TEXTBOXDIALOG                   147
#define IDD_COLORWINDOWS                148
#define FONTXBOXDIALOG                  149
#define IDD_ABOUTBOX                    153
#define IDD_MYMENU                      162
#define IDD_INFOHELPBOX                 162
#define IDMONTHSRANGE                   163
#define TXTPOPMENU                      199
#define IDMACROSET                      1000
#define TEXTBOXINPUT                    1001
#define IDC_LIST1                       1002
#define IDC_LIST2                       1004
#define IDC_BUTTON1                     1006
#define IDC_BUTTON2                     1007
#define IDC_BUTTON3                     1008
#define IDC_BUTTON4                     1009
#define IDC_BUTTON5                     1010
#define IDC_BUTTON6                     1011
#define IDC_BUTTON7                     1012
#define IDC_BUTTON8                     1013
#define IDC_EDIT1                       1015
#define EDITSCHAR                       1015
#define IDSPECIALCHAR                   1016
#define IDC_RICHEDIT21                  1017
#define IDC_RADIO2                      1019
#define IDC_RADIO3                      1020
#define IDC_RADIO4                      1021
#define IDC_EDIT2                       1025
#define IDC_EDITFONT                    1025
#define IDC_COMBO2                      1026
#define IDC_FONTTYPE                    1026
#define IDC_RADIO5                      1028
#define IDC_RSTRIKEOUT                  1028
#define IDC_COMBO3                      1030
#define IDC_FONTBKG                     1030
#define IDC_COMBO4                      1031
#define IDC_FONTCOLOR                   1031
#define IDC_RADIO6                      1032
#define IDC_SUBSCRIPT                   1032
#define IDC_RADIO7                      1033
#define IDC_RSUPERSCRIPT                1033
#define IDC_COMBO5                      1034
#define IDC_FUCOLOR                     1034
#define IDC_COMBO6                      1035
#define IDC_FUNDERLINE                  1035
#define IDC_RBOLD                       1036
#define IDC_RITALIC                     1037
#define IDC_RUNDERLINE                  1038
#define ID_SETTINGS                     32771
#define ID_COPY                         32772
#define ID_PASTE                        32773
#define ID_SAMPLEVAL_DELETE             32774
#define ID_SAMPLEVAL_CUT                32775
#define ID_SAMPLEVAL_SELECTALL          32776
#define ID_SAMPLEVAL_GETFONT            32777
#define ID_SAMPLEVAL_APPLYFONT          32778
#define ID_SAMPLEVAL_REMOVEFONT         32779
#define ID_DELETE                       32780
#define ID_CUT                          32781
#define ID_SELECTALL                    32782
#define ID_GETFONT                      32783
#define ID_APPLYFONT                    32784
#define ID_REMOVEFONT                   32785
#define ID_SAMPLEVAL_UNDO               32786
#define ID_SAMPLEVAL_REDO               32787
#define ID_UNDO                         32788
#define ID_REDO                         32789
#define ID_SAMPLEVAL_ZOOMIN             32790
#define ID_SAMPLEVAL_ZOOMOUT            32791
#define ID_Menu                         32792
#define ID_CHANGEFONT                   32793
#define FONTBOXDIALOG                   32793
#define ID_ZOOMIN                       32794
#define ID_ZOOMOUT                      32795
#define IDC_DATESELECT                  40001
#define IDM_ABOUT                       40002
#define IDDSCRIPTINPUT                  40003
#define IDMACROSSI                      40004
#define IDDSCRIPTINPUT2                 40004
#define IDWINDOWCOLOR                   40004
#define IDDATESSI                       40005
#define IDCHANGEMONTHSRG                40005
#define IDHELPSI                        40006
#define IDCHANGEDATASOURCE              40006
#define TXTSCRIPTINPUT                  40007
#define IDINFOSCRIPT                    40008
#define IDSAVESCRIPT                    40009
#define IDREMOVESCRIPT                  40010
#define TXTSCRIPTINPUT2                 40011
#define TXTSCRIPTSHOW                   40012
#define IDINFOSCRIPT2                   40013
#define TXTSCRIPTINPUT3                 40014
#define IDMONTHF                        40015
#define IDMONTHL                        40016
#define IDYEARF                         40017
#define IDYEARFs                        40017
#define IDYEARL                         40018
#define IDDAYF                          40019
#define IDDAYL                          40020
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
